apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: demo-pool
  namespace: metallb-system
spec:
  addresses:
    # replace the following with your IP address range
    - 192.168.67.100-192.168.67.110
