apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      nodePort: 30492
      # service
      port: 80
      # container
      targetPort: 80
  type: NodePort
